#sudo: required
language: python

cache: pip

env:
  - BUILD=release
  - BUILD=prerelease
  - BUILD=branches
  - BUILD=special

git:
  depth: 5

services:
  - docker

install:
  - docker pull noonedev/netbox:latest
  - docker-compose pull --parallel
  - docker-compose build --cache-from noonedev/netbox:latest

script:
  - docker-compose run netbox ./manage.py test

after_script:
  - docker-compose down

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./build-all.sh --push
